bot:
  name:  BirthdayBot
  username: test
  token: 5163332040:AAGiUXDIgu-qk4tsWxIgKY1BL9fNSkNnyLQ
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tbot
    jdbc-url: jdbc:postgresql://localhost:5432/tgbot_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect


  pingtask:
    url: https://www.google.com
    period: 120000